version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      # test
      - run: npm run test
      # build
      - run: npm run prod-webapp
  test-e2e-login:
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Repo Check 1
          command: |
            if [ "$CIRCLE_REPOSITORY_URL" == "git@github.com:blockstack/blockstack-browser.git" ]; then
              export TEST_E2E_GREP=login-to-hello-blockstack-app
              npm install && npm run test-e2e:browserstack
            else
              export TEST_E2E_GREP=login-to-hello-blockstack-app
              npm install && npm run test-e2e:localBuild
            fi
      - store_artifacts:
          path: /tmp/test-errors
  test-e2e-account-creation:
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Repo Check 2
          command: |
            if [ "$CIRCLE_REPOSITORY_URL" == "git@github.com:blockstack/blockstack-browser.git" ]; then
              export TEST_E2E_GREP=account-creation
              npm install && npm run test-e2e:browserstack
            else
              export TEST_E2E_GREP=account-creation
              npm install && npm run test-e2e:localBuild
            fi
      - store_artifacts:
          path: /tmp/test-errors
  test-e2e-account-recovery:
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Repo Check 3
          command: |
            if [ "$CIRCLE_REPOSITORY_URL" == "git@github.com:tim/blockstack-browser.git" ]; then
              export TEST_E2E_GREP=account-recovery
              npm install && npm run test-e2e:browserstack
            else
              export TEST_E2E_GREP=account-recovery
              npm install && npm run test-e2e:localBuild
            fi
      - store_artifacts:
          path: /tmp/test-errors
workflows:
  version: 2
  build_and_test_e2e_local_or_remote-e2e:
    jobs:
      - build
      - test-e2e-login
      - test-e2e-account-creation
      - test-e2e-account-recovery
